In [ ]:
words = open('/content/sample_data/names.txt').read().splitlines()

In [ ]:
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [ ]:
b = {}
for w in words[50:]:
    chrs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chrs, chrs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1

In [ ]:
sorted(b.items(), key = lambda kv: -kv[1])

[(('n', '<E>'), 6758),
 (('a', '<E>'), 6621),
 (('a', 'n'), 5434),
 (('<S>', 'a'), 4401),
 (('e', '<E>'), 3975),
 (('a', 'r'), 3259),
 (('e', 'l'), 3237),
 (('r', 'i'), 3030),
 (('n', 'a'), 2973),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2916),
 (('e', 'n'), 2674),
 (('l', 'a'), 2613),
 (('m', 'a'), 2588),
 (('<S>', 'm'), 2535),
 (('a', 'l'), 2527),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2472),
 (('i', 'a'), 2437),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2409),
 (('h', '<E>'), 2405),
 (('r', 'a'), 2353),
 (('a', 'h'), 2329),
 (('h', 'a'), 2240),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2049),
 (('a', 'y'), 2049),
 (('y', '<E>'), 2000),
 (('e', 'r'), 1956),
 (('n', 'n'), 1904),
 (('y', 'n'), 1824),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1694),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1651),
 (('a', 'i'), 1648),
 (('<S>', 'r'), 1638),
 (('a', 'm'), 1632),
 (('l', 'y'), 1584),
 (('<S>', 'l'), 1567),
 (('<S>', 'c'), 1538),
 (('<S>', 'e'), 1524),
 (('j', 'a'), 1473),
 (

In [ ]:
import torch

In [ ]:
N = torch.zeros((27, 27), dtype=torch.int32)


In [ ]:

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)} # string to indx, give char-->int a0. b1
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [ ]:

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1


In [ ]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [ ]:
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [ ]:

g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'j'

In [ ]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p


tensor([0.6064, 0.3033, 0.0903])

In [ ]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)


tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [ ]:
p.shape

torch.Size([3])

In [ ]:
P.shape

torch.Size([27, 27])

In [ ]:
P = (N+1).float()
P /= P.sum(1, keepdims=True)


In [ ]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):

  out = []
  ix = 0
  while True:
    p = P[ix]
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))


junide.
janasah.
p.
cony.
a.


In [ ]:

logLiklyHood = 0.0
n = 0

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logProb = torch.log(prob)
        logLiklyHood += logProb
        n += 1

print(f'{logLiklyHood=}')
nll = -logLiklyHood
print(f'{nll=}')

logLiklyHood=tensor(-559951.5625)
nll=tensor(559951.5625)


In [ ]:

xs, ys = [], []
for w in words[:1]:
    chs =['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


#Brodcasting

In [ ]:
#  creating P matrix which already has probabilities for each row

P = N.float()


"""
broadcasting rules:

1. align the shapes towards the right
27,27
27
becomes
27,27
   27

2. broadcasting is possible when any  of the individual sizes are either:
    -> equal
    -> missing
    -> or 1


# keepdims=True is important since we want to divide along the rows
# otherwise, we'll lose that row dimensionality and we'll end up diving along the cols

we need:
27, 27
27,  1
instead of
27,27
 1,27
"""
#P /= P.sum(dim=1, keepdims=True)


# Bigram Character Level Model

In [1]:
import torch
import string
import matplotlib.pyplot as plt
%matplotlib inline



In [2]:
words = open('/content/names.txt', 'r').read().splitlines()

In [3]:
tokens = ['.'] + list(string.ascii_lowercase)


In [4]:
stoi = {s:i for i, s in enumerate(tokens)} # string to index
itos = {i:s for s, i in stoi.items()}


In [5]:
N = torch.zeros((27,27), dtype=torch.int32)



In [6]:
for w in words:
    chrs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chrs, chrs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [7]:
P = (N+1).float() # adding 1 to remove zero counts to avoid log(0)
P /= P.sum(dim=1, keepdims=True)

In [13]:


g = torch.Generator().manual_seed(2147483647)
ix=0
for i in range(10):
    names = ''
    while True:
        p = P[ix,:]
        ix = torch.multinomial(p, num_samples=1 ,replacement=True, generator=g).item()
        names += itos[ix]
        if ix == 0:
            break
    print(names)


junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.


In [14]:
logLikelyHood = 0.0
for w in words:
    chrs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chrs,chrs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        logLikelyHood += logprob

nll = -logLikelyHood
normalized_nll = nll/len(words)
print(f"{nll=} {normalized_nll=}")


nll=tensor(559951.5625) normalized_nll=tensor(17.4805)
